pull_request_rules:
  - name: backport 1.x
    conditions:
      - label = backport-1.x
    actions:
      backport:
        branches:
          - 1.x
        assignees:
          - "{{ author }}"
  - name: backport 2.x
    conditions:
      - label = backport-2.x
    actions:
      backport:
        branches:
          - 2.x
        assignees:
          - "{{ author }}"
queue_rules:
  - merge_method: squash
    name: dev
  - merge_method: squash
    name: 1.x
    queue_conditions:
      - and:
          - base = 1.x
